### ISSUE TITLE
craftable barrier

### ISSUE THREAD

**Issue by xFedee** [MultiCoreNetwork/carpet-redcraft-addons#107]
barrier can be craftable, placed and destroyed, like the light block

**Comment by Pi3tro88** [comment]
if it is possible to make them destructible it would be less op

**Comment by BisUmTo** [comment]
> if it is possible to make them destructible it would be less op

With explosions?

**Comment by Pi3tro88** [comment]
> > if it is possible to make them destructible it would be less op
> 
> With explosions?

Also by hand
