### ISSUE TITLE
launching with essential addons crash the game

### ISSUE THREAD

**Issue by Pi3tro88** [MultiCoreNetwork/carpet-redcraft-addons#112]
launching with the latest version of Super-Santa's carpet Essential AddonsAddons (1.0.6) crash the game

[latest.log](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/files/7514329/latest.log)

**Comment by BisUmTo** [comment]
https://github.com/Super-Santa/EssentialAddons/blob/428d83ea3467f2f66aaa2efbec73dab068e69785/src/main/java/essentialaddons/mixins/essentialCarefulbreak/BlockMixin.java#L26

Need to have a look how to fix this conflict... @Super-Santa

**Comment by senseiwells** [comment]
Right this is because our Mixin is getting loaded first as you have `priority = 999`
And your mixin is required so it crashes, so just tagging it with `require = 0` will make it so only one redirect is applied
