### ISSUE TITLE
CraftableIce rule should be renamed into UnpackableIce

### ISSUE THREAD

**Issue by Pi3tro88** [MultiCoreNetwork/carpet-redcraft-addons#129]
packed and blue ice can be unpacked

**Comment by BisUmTo** [comment]
È un suggerimento?

**Comment by Pi3tro88** [comment]
Si ahahah

**Comment by BisUmTo** [comment]
Credo ci sia già: si chiama craftableIce

**Comment by BisUmTo** [comment]
La regola che permette di craftare il ghiaccio andrebbe unità con quella che permette di craftare il ghiaccio compresso;
Rinominando la regola in "UnpackableIce" o simile

**Comment by Pi3tro88** [comment]
Ma no, non c'è, l'ho messa perché non si può fare

**Comment by Pi3tro88** [comment]
ok lol ho scoperto che c'era già ma nello stone cutter, non crafting table
