### ISSUE TITLE
issues with carefulbreak with shulker boxes

### ISSUE THREAD

**Issue by Pi3tro88** [MultiCoreNetwork/carpet-redcraft-addons#142]
If you break a shulker box when shifting, so with carefulbreak the shulker remain with an “nbt data” and so it can’t be stacked with other boxes not taken with the carefulbreak

**Comment by BisUmTo** [comment]
Tecnicamente è un bug vanilla, ma possiamo fare una nuova regola che - se l'item ha tutti gli NBT di default - non li salva esplicitamente

**Comment by Pi3tro88** [comment]
Oki

**Comment by BisUmTo** [comment]
Fixed in https://github.com/Super-Santa/EssentialAddons
