### ISSUE TITLE
fast comparator crafting

### ISSUE THREAD

**Issue by Pi3tro88** [MultiCoreNetwork/carpet-redcraft-addons#165]
why there is a fast redstone crafting for the repeater but not for the comparator? 
poor comparator don't bully him

**Comment by BisUmTo** [comment]
Come la consigli? Non ci sono abbastanza slot per mettere tutte le torce...

**Comment by Pi3tro88** [comment]
uhm a questo non ci avevo pensato
penso non ci sia un modo
