### ISSUE TITLE
redcraft addons with essential addons still crash the game

### ISSUE THREAD

**Issue by Pi3tro88** [MultiCoreNetwork/carpet-redcraft-addons#171]
i already subtitted this issues and it was closed, but the problem does not seem solved, if i try to launch the game only with carpet mod and essential and recraft addons, the game crashes

[latest.log](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/files/7877551/latest.log)

**Comment by BisUmTo** [comment]
It looks like the last crash is a OpenGL related one...

**Comment by Pi3tro88** [comment]
ma?
non è lo stesso log

**Comment by Pi3tro88** [comment]
ups.. log sbagliato
