### ISSUE TITLE
redcraft addons with essential client crash  the game

### ISSUE THREAD

**Issue by Pi3tro88** [MultiCoreNetwork/carpet-redcraft-addons#175]
redcraft addons with senseiwells's Essential Client crash  the game
[latest.log](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/files/7890544/latest.log)

**Comment by BisUmTo** [comment]
Empty log...
Probably related to #112

**Comment by Pietr06** [comment]
riprovato e il log è uguale, idk why

**Comment by BisUmTo** [comment]
Persiste anche con la versione 1.4.57?

**Comment by Pietr06** [comment]
no, sembra fixato
