### ISSUE TITLE
barrier and light can't show particles in 1.18.1

### ISSUE THREAD

**Issue by xFedee** [MultiCoreNetwork/carpet-redcraft-addons#182]
![IMG_20220226_075404_879](https://user-images.githubusercontent.com/87451140/155833816-c0e97dc9-a1ef-46a3-a028-70f43dccbd22.jpg)
![IMG_20220226_075403_517](https://user-images.githubusercontent.com/87451140/155833822-c9a1c37b-f881-4811-8322-406c6511053c.jpg)

**Comment by BisUmTo** [comment]
@DukeEdivad05 can you fix it, please?

**Comment by DukeEdivad05** [comment]
> @DukeEdivad05 can you fix it, please?

Ok, quando ho tempo lo faccio
