### ISSUE TITLE
Deopped players can't run /player command on themselves

### ISSUE THREAD

**Issue by DukeEdivad05** [MultiCoreNetwork/carpet-redcraft-addons#21]
Gli aiutanti non possono fare /player <playername> attack interval <ticks> su se stessi

**Comment by BisUmTo** [comment]
Purtroppo questo comando non è gestito dall'estensione, sarebbe da sovrascrivere il funzionamento del comando `/player` al fine di aggiungere un regola per controllare i singoli sottocomandi...

Quali sono i comandi che si vorrebbero esporre a tutti da usare su se stessi (oltre ad `attack`)?
