### ISSUE TITLE
Graves doesn't generate sometimes

### ISSUE THREAD

**Issue by BisUmTo** [MultiCoreNetwork/carpet-redcraft-addons#4]
A volte la tomba non viene generata alla morte.
Non in grado di replicare.

[Nessun video in allegato]

**Comment by TuTuiaRed3** [comment]
La tomba non si e` generata la prima volta una settimana fa e il problema si e` riverificato oggi. La prima volta e` capitato nel nether dove sono caduto su un promontorio sopra un lago di lava e ho perso la maggior parte delle cose (alcune erano in netherite quindi si sono salvate nella lava e altre sono rimaste sul promontorio). La seconda e` capitata in una colonna d`acqua con le bolle ucciso da un vex.

**Comment by BisUmTo** [comment]
Dovrebbe essere risolto nelle nuove versioni
