### ISSUE TITLE
[FEATURE REQUEST] A way to put blocks/item in armor stand head.

### ISSUE THREAD

**Issue by NAPPUS** [MultiCoreNetwork/carpet-redcraft-addons#60]
Could be super nice to have a way to equip blocks and item in the armor stand head, this can be used as decoration. (example: a magic block equiped in an invisible and rotating armor stand)

**Comment by BisUmTo** [comment]
Related to #18

**Comment by BisUmTo** [comment]
Dovrebbe essere stato risolto
