### ISSUE TITLE
Issue with some (Not all) nether portals working from Nether -> Overworld

### ISSUE THREAD

**Issue by cherie535** [MultiCoreNetwork/carpet-redcraft-addons#69]
Hello,

We are using carpet-redcraft-addons with the latest Carpet release.

We are seeing some odd behaviour with Nether portals though, and thru process of elimination, we have determined it might be this Carpet Addon.

Bascially, transportation from the Nether to the Overworld on *some* portals does not work.  That is to say that 4 seconds elapses and you do not go anywhere.  Similarly, mobs cant go through those portals from the Nether to the Overworld.

All portals from the overworld to The Nether work.

I suspect that this may have something to do with the Redcraft2Teleport rule, but disabling it has no effect.

**Comment by BisUmTo** [comment]
Which version are you playing on?

**Comment by cherie535** [comment]
Hi,
We are on 1.17

**Comment by BisUmTo** [comment]
The last release should fix it 😉
Let me know
